### ISSUE TITLE
Cannot read property 'host' of undefined When using queueURL

### ISSUE THREAD

**Issue by xdrago1** [hazemhagrass/advanced-sitemap-generator#8]
**Do you want to request a *feature* or report a *bug*?**
Bugreport

**What is the current behavior?**
Generator is aborting when adding a URL with queueURL. I am getting job offers from the database and generate some urls for that. But it does not work at all.

I have the same outcopme without the database thing as soon as I try to ad ANY url via queueURL. So something seems to be broken with that?

```
(node:28284) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'host' of undefined
    at shouldPageBeFetched (...\node_modules\advanced-sitemap-generator\src\createCrawler.js:83:73)
    at ...\node_modules\advanced-sitemap-generator\src\createCrawler.js:90:16
    at ...\node_modules\advanced-sitemap-generator\node_modules\simplecrawler\lib\crawler.js:1105:13
    at ...\node_modules\advanced-sitemap-generator\node_modules\async\dist\async.js:1918:17
    at eachOfArrayLike (...\node_modules\advanced-sitemap-generator\node_modules\async\dist\async.js:500:13)
    at eachOf (...\node_modules\advanced-sitemap-generator\node_modules\async\dist\async.js:551:16)
    at awaitable (...\node_modules\advanced-sitemap-generator\node_modules\async\dist\async.js:208:32)
    at ...\node_modules\advanced-sitemap-generator\node_modules\async\dist\async.js:1917:13
    at Object.every (...\node_modules\advanced-sitemap-generator\node_modules\async\dist\async.js:2357:57)
    at Object.awaitable (...\node_modules\advanced-sitemap-generator\node_modules\async\dist\async.js:208:32)
(node:28284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://n
odejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)

```

**If the current behavior is a bug, please provide the steps to reproduce.**
```
 async initSitemap() {
    // create generator
    const generator = SitemapGenerator('https://test.medboerse.de', {
      stripQuerystring: false,
      excludeFileTypes: ['gif', 'jpg', 'jpeg', 'png', 'ico', 'bmp', 'ogg', 'webp', 'mp4', 'webm', 'mp3', 'ttf',
        'woff', 'json', 'rss', 'atom', 'gz', 'zip', 'rar', '7z', 'css', 'js', 'gzip', 'exe', 'svg',
        'xml'],
      ignoreHreflang: false,
      maxDepth: 0,
      filepath: path.join(process.cwd(), 'sitemap.xml'),

    });

    const offers = await this.entityManager.find(JobOfferEntity, {
      where: { isApproved: true, isActive: true },
      relations: ['subjectCategories', 'jobPositions', 'workplace', 'region'],
    });

    for (const job of offers) {
      console.log(job.id)
      generator.queueURL('https://test.myurl.de/stellenmarkt/job/');
      generator.queueURL('https://test.myurl.de/jobs/job/');
    }

// register event listeners
    generator.on('done', () => {
      // sitemaps created
    });

    generator.on('add', (url) => {
      // this.logger.debug(url);
    });

    generator.on('error', (error) => {
      this.logger.error(error);
    });

    generator.on('ignore', (url) => {
      // this.logger.error('IGNORED: ' + url);

    });

// start the crawler
    generator.start();
  }

```

**What is the expected behavior?**

**Comment by xdrago1** [comment]
Figured out it is because of the subdomain. Your algorithm cannot read the host from that?

**Comment by xdrago1** [comment]
I use a workaround til you fixed that:

In your createCrawler.js:
```
    if(!crawler) {
      console.log('no crawler defined');
    }
    if(!referrerQueueItem) {
      console.log('no referrerQueueItem defined');
    }
    const isDomainAllowed = options.filterByDomain ? (referrerQueueItem ? (referrerQueueItem.host === crawler.host) : true) : true;
```
